package Vistas;

import Conexion.Conexionmysql;
import controlador.Ctr_CofiguracionFacturas;
import java.awt.Dimension;
import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.ConfiguracionFacturas;

public class InterConfiguracionFacturas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterConfiguracionFacturas
     */
    public InterConfiguracionFacturas() {
        initComponents();
        this.setSize(new Dimension(900, 500));
        this.setTitle("Configuracion Facturas");

        // metodo para insertar imagen por medio de codigo
        ImageIcon wallpaper = new ImageIcon("src/imagenes/fondo3.jpg");
        Icon Icono = new ImageIcon(wallpaper.getImage().getScaledInstance(900, 500, WIDTH));
        jLabel_wallpaper.setIcon(Icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_prefijo = new javax.swing.JTextField();
        txt_numeroinicial = new javax.swing.JTextField();
        txt_impuesto = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_piePagina = new javax.swing.JTextArea();
        jButton_SeleccioneLogo = new javax.swing.JButton();
        jButton_GuardarConfiguracion = new javax.swing.JButton();
        jButton_CancelarConfiguracionn = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Configuracion Facturas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Configuracion Facturas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 280, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nombre de la Empresa:");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 60, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Direccion:");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 100, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Telefono:");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 140, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Logo:");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Peine de Pagina:");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 220, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Prefijo:");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Numero Inicial:");
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Porcentaje Impuesto:");
        jLabel9.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Porcenteje Descuento:");
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_nombre.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 60, -1, -1));

        txt_direccion.setBackground(new java.awt.Color(255, 255, 255));
        txt_direccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_direccion.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 100, -1, -1));

        txt_telefono.setBackground(new java.awt.Color(255, 255, 255));
        txt_telefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_telefono.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 140, -1, -1));

        txt_prefijo.setBackground(new java.awt.Color(255, 255, 255));
        txt_prefijo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_prefijo.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txt_prefijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        txt_numeroinicial.setBackground(new java.awt.Color(255, 255, 255));
        txt_numeroinicial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_numeroinicial.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txt_numeroinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        txt_impuesto.setBackground(new java.awt.Color(255, 255, 255));
        txt_impuesto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_impuesto.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txt_impuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        txt_descuento.setBackground(new java.awt.Color(255, 255, 255));
        txt_descuento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_descuento.setPreferredSize(new java.awt.Dimension(200, 30));
        getContentPane().add(txt_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        txt_piePagina.setBackground(new java.awt.Color(255, 255, 255));
        txt_piePagina.setColumns(20);
        txt_piePagina.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_piePagina.setRows(5);
        jScrollPane1.setViewportView(txt_piePagina);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 220, 220, -1));

        jButton_SeleccioneLogo.setBackground(new java.awt.Color(255, 255, 255));
        jButton_SeleccioneLogo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_SeleccioneLogo.setForeground(new java.awt.Color(0, 0, 0));
        jButton_SeleccioneLogo.setText("Seleccione logo");
        jButton_SeleccioneLogo.setPreferredSize(new java.awt.Dimension(210, 40));
        jButton_SeleccioneLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SeleccioneLogoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_SeleccioneLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 180, 200, 30));

        jButton_GuardarConfiguracion.setBackground(new java.awt.Color(0, 117, 12));
        jButton_GuardarConfiguracion.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_GuardarConfiguracion.setForeground(new java.awt.Color(0, 0, 0));
        jButton_GuardarConfiguracion.setText("Guardar configuracion");
        jButton_GuardarConfiguracion.setPreferredSize(new java.awt.Dimension(210, 40));
        jButton_GuardarConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GuardarConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        jButton_CancelarConfiguracionn.setBackground(new java.awt.Color(252, 17, 11));
        jButton_CancelarConfiguracionn.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton_CancelarConfiguracionn.setForeground(new java.awt.Color(0, 0, 0));
        jButton_CancelarConfiguracionn.setText("Guardar configuracion");
        jButton_CancelarConfiguracionn.setActionCommand("Cancelar Configuracion");
        jButton_CancelarConfiguracionn.setPreferredSize(new java.awt.Dimension(210, 40));
        jButton_CancelarConfiguracionn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarConfiguracionnActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_CancelarConfiguracionn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, -1, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_GuardarConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarConfiguracionActionPerformed
        // Recoger los datos ingresados en los campos de texto
        String nombreEmpresa = txt_nombre.getText();
        String direccion = txt_direccion.getText();
        String telefono = txt_telefono.getText();
        String prefijo = txt_prefijo.getText();
        String numeroInicial = txt_numeroinicial.getText();
        String impuesto = txt_impuesto.getText();
        String descuento = txt_descuento.getText();
        String piePagina = txt_piePagina.getText();
        // Asumiendo que el logo es cargado en un arreglo de bytes
        byte[] logo = null; // Aquí deberías cargar el logo si es necesario

        // Validar que no haya campos vacíos
        if (nombreEmpresa.isEmpty() || direccion.isEmpty() || telefono.isEmpty() || prefijo.isEmpty()
                || numeroInicial.isEmpty() || impuesto.isEmpty() || descuento.isEmpty() || piePagina.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que los valores numéricos sean válidos
        try {
            int numInicial = Integer.parseInt(numeroInicial);
            double porcentajeImpuesto = Double.parseDouble(impuesto);
            double porcentajeDescuento = Double.parseDouble(descuento);

            // Crear el objeto ConfiguracionFacturas con los valores ingresados
            ConfiguracionFacturas configuracion = new ConfiguracionFacturas();
            configuracion.setNombre_empresa(nombreEmpresa);
            configuracion.setDireccion(direccion);
            configuracion.setTelefono(telefono);
            configuracion.setPrefijo(prefijo);
            configuracion.setNumero_inicial(numInicial);
            configuracion.setPorcentaje_impuesto(porcentajeImpuesto);
            configuracion.setPorcentaje_descuento(porcentajeDescuento);
            configuracion.setPie_pagina(piePagina);
            configuracion.setLogo(logo);  // Asigna el logo si lo tienes

            // Usar el controlador para guardar la configuración en la base de datos
            Ctr_CofiguracionFacturas controlConfiguracion = new Ctr_CofiguracionFacturas();
            controlConfiguracion.configurarEncabezado(configuracion.getNombre_empresa(), configuracion.getDireccion(), configuracion.getTelefono(), "ruta_logo");  // Modifica "ruta_logo" con la ruta o el manejo real del logo
            controlConfiguracion.configurarPieDePagina(configuracion.getPie_pagina());
            controlConfiguracion.configurarNumeracionFactura(configuracion.getPrefijo(), configuracion.getNumero_inicial());
            controlConfiguracion.configurarImpuesto(configuracion.getPorcentaje_impuesto());
            controlConfiguracion.configurarDescuento(configuracion.getPorcentaje_descuento());

            JOptionPane.showMessageDialog(this, "Configuración guardada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Limpiar los campos después de guardar
            txt_nombre.setText("");
            txt_direccion.setText("");
            txt_telefono.setText("");
            txt_prefijo.setText("");
            txt_numeroinicial.setText("");
            txt_impuesto.setText("");
            txt_descuento.setText("");
            txt_piePagina.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos en los campos de número inicial, impuesto y descuento.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_GuardarConfiguracionActionPerformed

    private void jButton_SeleccioneLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SeleccioneLogoActionPerformed
        // Crear un JFileChooser para seleccionar el archivo de imagen
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccione un logo");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Filtro para permitir solo archivos de imagen
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de imagen", "jpg", "jpeg", "png", "gif");
        fileChooser.setFileFilter(filter);

        // Mostrar el diálogo de selección de archivo
        int result = fileChooser.showOpenDialog(this);

        // Comprobar si el usuario seleccionó un archivo
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();

            // Cargar y escalar la imagen seleccionada para mostrarla en un JLabel
            ImageIcon icon = new ImageIcon(filePath);
            Icon scaledIcon = new ImageIcon(icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH));

            // Mostrar el logo en un JLabel o cualquier otro componente
            jLabel5.setIcon(scaledIcon);

            // Guardar la ruta del archivo para su posterior uso (como guardarlo en la base de datos)
            // Por ejemplo, puedes almacenar esta ruta en una variable global o guardar en la base de datos
            System.out.println("Logo seleccionado: " + filePath);
        } else {
            JOptionPane.showMessageDialog(this, "No se seleccionó ningún archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SeleccioneLogoActionPerformed

    private void jButton_CancelarConfiguracionnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarConfiguracionnActionPerformed
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_telefono.setText("");
        txt_prefijo.setText("");
        txt_numeroinicial.setText("");
        txt_impuesto.setText("");
        txt_descuento.setText("");
        txt_piePagina.setText("");
    }//GEN-LAST:event_jButton_CancelarConfiguracionnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CancelarConfiguracionn;
    private javax.swing.JButton jButton_GuardarConfiguracion;
    private javax.swing.JButton jButton_SeleccioneLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_impuesto;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numeroinicial;
    private javax.swing.JTextArea txt_piePagina;
    private javax.swing.JTextField txt_prefijo;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
