package Vistas;

import controlador.Ctr_Proveedor;
import java.awt.Dimension;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import modelo.Proveedor;

public class InterProveedor extends javax.swing.JInternalFrame {

    int obtenerIdCategoriaCmbox = 0;

    public InterProveedor() {
        initComponents();
        this.setSize(new Dimension(500, 400));
        this.setTitle("Nuevo Producto");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        jComboBox_seleccione_estado = new javax.swing.JComboBox<>();
        jButton_guardarProveedor = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_wall_paper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nuevo Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 140, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Nombre:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Direccion:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Telefono:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Descripcion:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Estado:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, -1));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 210, -1));

        txt_direccion.setBackground(new java.awt.Color(255, 255, 255));
        txt_direccion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, -1));

        txt_telefono.setBackground(new java.awt.Color(255, 255, 255));
        txt_telefono.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 210, -1));

        txt_correo.setBackground(new java.awt.Color(255, 255, 255));
        txt_correo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, -1));

        txt_descripcion.setBackground(new java.awt.Color(255, 255, 255));
        txt_descripcion.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 210, -1));

        jComboBox_seleccione_estado.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_seleccione_estado.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_seleccione_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estado:", "Activo", "Inactivo" }));
        jComboBox_seleccione_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_seleccione_estadoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_seleccione_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 210, -1));

        jButton_guardarProveedor.setBackground(new java.awt.Color(0, 255, 255));
        jButton_guardarProveedor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_guardarProveedor.setForeground(new java.awt.Color(5, 65, 5));
        jButton_guardarProveedor.setText("Guardar Proveedor");
        jButton_guardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_guardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 150, 40));

        jButton_Cancelar.setBackground(new java.awt.Color(0, 255, 255));
        jButton_Cancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton_Cancelar.setForeground(java.awt.Color.red);
        jButton_Cancelar.setText("Cancelar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 150, 40));

        jLabel_wall_paper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel_wall_paper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarProveedorActionPerformed
        Proveedor proveedor = new Proveedor();
        Ctr_Proveedor controlProveedor = new Ctr_Proveedor();
        String estado = jComboBox_seleccione_estado.getSelectedItem().toString().trim();

        // Validar que no hayan campos vacíos
        if (txt_nombre.getText().equals("") || txt_direccion.getText().equals("") || txt_correo.getText().equals("") || txt_telefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        } else {
            // Validar existencia del proveedor
            if (!controlProveedor.existeProveedor(txt_nombre.getText().trim())) {
                if (estado.equalsIgnoreCase("Seleccione estado:")) {
                    JOptionPane.showMessageDialog(null, "Seleccione el estado");
                } else {
                    try {
                        // Asignar valores al proveedor
                        proveedor.setNombre(txt_nombre.getText().trim());
                        proveedor.setDireccion(txt_direccion.getText().trim());
                        proveedor.setTelefono(txt_telefono.getText().trim());
                        proveedor.setEmail(txt_correo.getText().trim());
                        proveedor.setDescripcion(txt_descripcion.getText().trim());
                        proveedor.setEstado(estado);

                        // Intentar guardar el proveedor
                        if (controlProveedor.guardarProveedores(proveedor)) {
                            JOptionPane.showMessageDialog(null, "Registro guardado");

                            // Limpiar campos solo después de un guardado exitoso
                            this.Limpiar();

                            // Restablecer el valor del ComboBox del estado
                            this.jComboBox_seleccione_estado.setSelectedItem("Seleccione estado:");
                        } else {
                            JOptionPane.showMessageDialog(null, "Error al guardar");
                        }

                    } catch (HeadlessException | NumberFormatException e) {
                        System.out.println("Error en: " + e);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "El proveedor ya existe");
            }
        }
    }//GEN-LAST:event_jButton_guardarProveedorActionPerformed

    private void jComboBox_seleccione_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_seleccione_estadoActionPerformed
        // Obtener el estado seleccionado
        String estadoSeleccionado = jComboBox_seleccione_estado.getSelectedItem().toString();

        // Validar que no sea la opción predeterminada
        if (estadoSeleccionado.equals("Seleccione estado:")) {
            
        } else {
            // Puedes almacenar o usar la selección en otra lógica si es necesario
            System.out.println("Estado seleccionado: " + estadoSeleccionado);
        }
    }//GEN-LAST:event_jComboBox_seleccione_estadoActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        // Limpiar todos los campos del formulario
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_correo.setText("");
        txt_telefono.setText("");
        txt_descripcion.setText("");
        jComboBox_seleccione_estado.setSelectedItem("Seleccione estado:");
    }//GEN-LAST:event_jButton_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_guardarProveedor;
    private javax.swing.JComboBox<String> jComboBox_seleccione_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wall_paper;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    private void Limpiar() {
        // Limpiar todos los campos del formulario
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_correo.setText("");
        txt_telefono.setText("");
        txt_descripcion.setText("");
        jComboBox_seleccione_estado.setSelectedItem("Seleccione estado:");
    }

}
