package Vistas;

import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

public class MenuInventario extends javax.swing.JFrame {

    

    public static JDesktopPane jDesktopPane_menuInventario;

    public MenuInventario() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Inventario");
        this.setLayout(null);
        jDesktopPane_menuInventario = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menuInventario.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menuInventario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_AgregarProducto = new javax.swing.JMenuItem();
        jMenuItem_GestionarProducto = new javax.swing.JMenuItem();
        jMenuItem_ActualizarStock = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_AgregarCategoria = new javax.swing.JMenuItem();
        jMenuItem_GestionarCategoria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_AgregarProveedor = new javax.swing.JMenuItem();
        jMenuItem_GestionarProveedor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_ReportesStock_bajo = new javax.swing.JMenuItem();
        jMenuItem_ReporteVentasPorProducto = new javax.swing.JMenuItem();
        jMenuItem_ReporteInventarioTotal = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_RegistrarDevolucion = new javax.swing.JMenuItem();
        jMenuItem_GestionarDevolucion = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_CerrarSesion = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        jMenu1.setText("productos");
        jMenu1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_AgregarProducto.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_AgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo-producto.png"))); // NOI18N
        jMenuItem_AgregarProducto.setText("Agregar Producto");
        jMenuItem_AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AgregarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_AgregarProducto);

        jMenuItem_GestionarProducto.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_GestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        jMenuItem_GestionarProducto.setText("GestionarProducto");
        jMenuItem_GestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_GestionarProducto);

        jMenuItem_ActualizarStock.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_ActualizarStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jMenuItem_ActualizarStock.setText("Actualizar Stock");
        jMenuItem_ActualizarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ActualizarStockActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_ActualizarStock);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        jMenu2.setText(" Categorías ");
        jMenu2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_AgregarCategoria.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_AgregarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        jMenuItem_AgregarCategoria.setText("Agregar Categoria");
        jMenuItem_AgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AgregarCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_AgregarCategoria);

        jMenuItem_GestionarCategoria.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_GestionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/categorias.png"))); // NOI18N
        jMenuItem_GestionarCategoria.setText("Gestionar Categoria");
        jMenuItem_GestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_GestionarCategoria);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores1.png"))); // NOI18N
        jMenu3.setText("Proveedores");
        jMenu3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_AgregarProveedor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_AgregarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        jMenuItem_AgregarProveedor.setText("Agregar Proveedor");
        jMenuItem_AgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_AgregarProveedorActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_AgregarProveedor);

        jMenuItem_GestionarProveedor.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_GestionarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores1.png"))); // NOI18N
        jMenuItem_GestionarProveedor.setText("Gestionar Proveedor");
        jMenuItem_GestionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarProveedorActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_GestionarProveedor);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportes.png"))); // NOI18N
        jMenu5.setText("Reportes");
        jMenu5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_ReportesStock_bajo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_ReportesStock_bajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenuItem_ReportesStock_bajo.setText("Stock Bajo");
        jMenuItem_ReportesStock_bajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReportesStock_bajoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_ReportesStock_bajo);

        jMenuItem_ReporteVentasPorProducto.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_ReporteVentasPorProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenuItem_ReporteVentasPorProducto.setText("Ventas Por Producto");
        jMenuItem_ReporteVentasPorProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReporteVentasPorProductoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_ReporteVentasPorProducto);

        jMenuItem_ReporteInventarioTotal.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_ReporteInventarioTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte1.png"))); // NOI18N
        jMenuItem_ReporteInventarioTotal.setText("Inventario Total");
        jMenuItem_ReporteInventarioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ReporteInventarioTotalActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_ReporteInventarioTotal);

        jMenuBar1.add(jMenu5);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devoluciones32.png"))); // NOI18N
        jMenu7.setText("Devoluciones");
        jMenu7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_RegistrarDevolucion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_RegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devoluciones32.png"))); // NOI18N
        jMenuItem_RegistrarDevolucion.setText("Registrar Devolucion");
        jMenuItem_RegistrarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RegistrarDevolucionActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_RegistrarDevolucion);

        jMenuItem_GestionarDevolucion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_GestionarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/devoluciones32.png"))); // NOI18N
        jMenuItem_GestionarDevolucion.setText("Gestionar Devolucion");
        jMenuItem_GestionarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_GestionarDevolucionActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem_GestionarDevolucion);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenu8.setText("Cerrar Sesion");
        jMenu8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem_CerrarSesion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem_CerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        jMenuItem_CerrarSesion.setText("Cerrar Sesion");
        jMenuItem_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_CerrarSesionActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem_CerrarSesion);

        jMenuBar1.add(jMenu8);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver1.png"))); // NOI18N
        jMenu4.setText("Regresar");
        jMenu4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(180, 50));

        jMenuItem2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver1.png"))); // NOI18N
        jMenuItem2.setText("Menu principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_AgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AgregarCategoriaActionPerformed
        InterCategorias interCategorias = new InterCategorias();
        jDesktopPane_menuInventario.add(interCategorias);
        interCategorias.setVisible(true);

    }//GEN-LAST:event_jMenuItem_AgregarCategoriaActionPerformed

    private void jMenuItem_GestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarCategoriaActionPerformed
        InterGestionarCategorias interGestionarCategorias = new InterGestionarCategorias();
        jDesktopPane_menuInventario.add(interGestionarCategorias);
        interGestionarCategorias.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarCategoriaActionPerformed

    private void jMenuItem_AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AgregarProductoActionPerformed
        InterProducto interProducto = new InterProducto();
        jDesktopPane_menuInventario.add(interProducto);
        interProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AgregarProductoActionPerformed

    private void jMenuItem_GestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarProductoActionPerformed
        InterGestionarProductos gestionarProductos = new InterGestionarProductos();
        jDesktopPane_menuInventario.add(gestionarProductos);
        gestionarProductos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarProductoActionPerformed

    private void jMenuItem_ActualizarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ActualizarStockActionPerformed
        InterActualizarStock actualizaStock = new InterActualizarStock();
        jDesktopPane_menuInventario.add(actualizaStock);
        actualizaStock.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ActualizarStockActionPerformed

    private void jMenuItem_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_CerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_CerrarSesionActionPerformed

    private void jMenuItem_AgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_AgregarProveedorActionPerformed
        InterProveedor proveedor = new InterProveedor();
        jDesktopPane_menuInventario.add(proveedor);
        proveedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem_AgregarProveedorActionPerformed

    private void jMenuItem_GestionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarProveedorActionPerformed
        InterGestionarProveedores gestionarproveedor = new InterGestionarProveedores();
        jDesktopPane_menuInventario.add(gestionarproveedor);
        gestionarproveedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarProveedorActionPerformed

    private void jMenuItem_ReportesStock_bajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReportesStock_bajoActionPerformed
        InterStockbajo stockBajo = new InterStockbajo();
        jDesktopPane_menuInventario.add(stockBajo);
        stockBajo.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ReportesStock_bajoActionPerformed

    private void jMenuItem_ReporteVentasPorProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReporteVentasPorProductoActionPerformed
        InterVentasPorProductos ventasPorProductos = new InterVentasPorProductos();
        jDesktopPane_menuInventario.add(ventasPorProductos);
        ventasPorProductos.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ReporteVentasPorProductoActionPerformed

    private void jMenuItem_ReporteInventarioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ReporteInventarioTotalActionPerformed
        InterReporteInventarioTotal inventarioTotal = new InterReporteInventarioTotal();
        jDesktopPane_menuInventario.add(inventarioTotal);
        inventarioTotal.setVisible(true);
    }//GEN-LAST:event_jMenuItem_ReporteInventarioTotalActionPerformed

    private void jMenuItem_RegistrarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RegistrarDevolucionActionPerformed
        InterDevolucion devolucion = new InterDevolucion();
        jDesktopPane_menuInventario.add(devolucion);
        devolucion.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RegistrarDevolucionActionPerformed

    private void jMenuItem_GestionarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_GestionarDevolucionActionPerformed
        InterGestionarDevolucion gestionardevolucion = new InterGestionarDevolucion();
        jDesktopPane_menuInventario.add(gestionardevolucion);
        gestionardevolucion.setVisible(true);
    }//GEN-LAST:event_jMenuItem_GestionarDevolucionActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);  // Mostrar la ventana de la página principal

        this.dispose();  // Cerrar la ventana actual
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_ActualizarStock;
    private javax.swing.JMenuItem jMenuItem_AgregarCategoria;
    private javax.swing.JMenuItem jMenuItem_AgregarProducto;
    private javax.swing.JMenuItem jMenuItem_AgregarProveedor;
    private javax.swing.JMenuItem jMenuItem_CerrarSesion;
    private javax.swing.JMenuItem jMenuItem_GestionarCategoria;
    private javax.swing.JMenuItem jMenuItem_GestionarDevolucion;
    private javax.swing.JMenuItem jMenuItem_GestionarProducto;
    private javax.swing.JMenuItem jMenuItem_GestionarProveedor;
    private javax.swing.JMenuItem jMenuItem_RegistrarDevolucion;
    private javax.swing.JMenuItem jMenuItem_ReporteInventarioTotal;
    private javax.swing.JMenuItem jMenuItem_ReporteVentasPorProducto;
    private javax.swing.JMenuItem jMenuItem_ReportesStock_bajo;
    // End of variables declaration//GEN-END:variables
}
